# Generated by Django 4.1.2 on 2022-10-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='género',
            new_name='genero',
        ),
    ]
